#!/bin/sh
#curl -v -u TODO:api_token \
#    -H "Content-Type: application/json" \
#    -d '{"time_entry":{"description":"Email","tags":["billed"],"duration":1200,"start":"2013-03-05T07:58:58.000Z","pid":460844,"created_with":"curl"}}' \
#    -X POST https://www.toggl.com/api/v8/time_entries/start
#
TOGGLTOKEN=TODO
TOGGLAPI="https://www.toggl.com/api/v8/"
TOGGLCN="\"created_with\":\"togglebash\""
FULLNAME=TODO
JOBTITLE=TODO
HIPCHAT_EMAIL=TODO
HIPCHAT_MENTION_NAME=TODO
HIPCHAT_AUTH_TOKEN=TODO
HIPCHAT_TIMEZONE=Pacific/Honolulu

__toggl_call() {
  curl -s -u "$TOGGLTOKEN:api_token" \
  -H 'Content-type: application/json' \
  "$3" -X $1 "$TOGGLAPI$2"
}

__toggl_get() {
  __toggl_call 'GET' "$1"
}

__toggl_post() {
  __toggl_call 'POST' "$1" "-d $2"
}

__toggl_put() {
  __toggl_call 'PUT' "$1"
}

__toggl_current() {
  __toggl_get 'time_entries/current'
}

# Post to toggl
ID=`__toggl_current | python -c 'import json, sys
x = json.loads(sys.stdin.read())
print x.get("data", {}).get("id", "")'`

__toggl_put "time_entries/$ID/stop"

# Post to hipchat
curl -s \
  -X PUT \
  -H 'Content-type: application/json' \
  -d "{\"name\":\"$FULLNAME\",\"title\":\"$JOBTITLE\",\"timezone\":\"$HIPCHAT_TIMEZONE\",\"email\":\"$HIPCHAT_EMAIL\",\"mention_name\":\"$HIPCHAT_MENTION_NAME\",\"presence\":{\"show\":away,\"status\":\"$HIPCHATSTATUS\"}}" \
  "https://api.hipchat.com/v2/user/$HIPCHAT_EMAIL?auth_token=$HIPCHAT_AUTH_TOKEN"
